### ISSUE TITLE
build failure on OCaml 4.03, 4.04+beta

### ISSUE THREAD

**Issue by gasche** [zoggy/xtmpl#5]
opam-builder reports [build failures](http://opam.ocamlpro.com/builder/html/report-full.html#xtmpl) for recent xtmpl versions 0.{11,12,13}, I think due to a ppx issue. opam-builder report:
  <http://opam.ocamlpro.com/builder/html/xtmpl/xtmpl.0.13.0/8a5c5f5a155a9f601ea10430e803462b>

```
File "xtmpl_xml.ml", line 173, characters 78-79:
Error: Syntax error: pattern expected.
make: *** [xtmpl_xml.cmo] Error 2
```

**Comment by zoggy** [comment]
I made a 0.14.0 release: https://github.com/ocaml/opam-repository/pull/7226
